### ISSUE TITLE
how to access the connect object?

### ISSUE THREAD

**Issue by devzer01** [apigee-127/swagger-connect#1]
hi trying to figure out how i can access the connect object from swagger-connect. I am trying to manipulate some response headers. 

more specifically something like 
```
app.all("*", function (req, res) {
res.header "Content-Type", "content-type";
next();
});
```

**Comment by theganyo** [comment]
You already have it defined and available from the top of your app.js file. It looks like this:

```
var app = require('connect')();
```

**Comment by devzer01** [comment]
oops big brain-fart!!! sorry. thanks :)
